# Qwen3-TTS API 服务配置
server:
  host: "0.0.0.0"
  port: 8420

model:
  model_path: "C:/Users/s/.cache/huggingface/hub/models--Qwen--Qwen3-TTS-12Hz-1.7B-CustomVoice/snapshots/0c0e3051f131929182e2c023b9537f8b1c68adfe"
  device_map: "cpu"
  torch_dtype: "float32"

output:
  base_dir: "output_audio"
